config/routes.rb
Rails.application.routes.draw do
  get 'products/buy'
  get 'products/index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'creditcards', to: 'users/registrations#new_creditcard'
    post 'creditcards', to: 'users/registrations#create_creditcard'
  end
  root 'products#index'

 
  
    resources :users, only: [:show, :edit, :update]do
      member do
        get 'profile'
        patch 'profile_update'
        get 'logout'
      end
    end
  resources :products ,only: [:index,:new,:show,:create]do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      post 'purchase'
      get 'purchased'
      get 'buy'
      get 'reserve'
      patch 'reserved'
      patch 'reserve_cancel'
    end
end   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname,:family_name,:first_name,:family_name_kana,:first_name_kana,:birthday, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 7 }, format: { with: /(?=.*\d+.*)(?=.*[a-zA-Z]+.*)./ }
  has_one :address
  has_one :creditcard

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end
  

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end

    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    session["address"] = @address.attributes
    @creditcard = @user.build_creditcard
    render :new_credit_card
  end

  def new_credit_card
  end

  def create_creditcard
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(session["address"])
    Payjp.api_key = Rails.application.secrets.payjp_access_key
    if params['payjpToken'].blank?
      redirect_to action: "new"
    else
      # 顧客情報をPAY.JPに登録。
      customer = Payjp::Customer.create(
        description: 'test', 
        email: @user.email,
        card: params['payjpToken'], 
      )
    end
    @creditcard = Creditcard.new(creditcard_params)
    unless @creditcard.valid?
      flash.now[:alert] = @creditcard.errors.full_messages
      # render :new_credit_card and return
    end
    @user.build_address(@address.attributes)
    @user.build_creditcard(@creditcard.attributes)
    if @user.save
      sign_in(:user, @user)
    else
      render :new
    end
  end

  protected
  def address_params
    params.require(:address).permit(:address,:postal_code, :prefecture,:city,:apartment)
  end

  def creditcard_params
    params.require(:creditcard).permit(:card_number,:card_year, :card_month, :card_pass,:card_company)
  end



  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit,:profile,:profile_update,:logout]
  before_action :set_address, only: [:edit, :update]

  def show
  end

  def edit
  end

  def logout
  end

  def update
    if @address.update(address_params)
      redirect_to edit_user_path(@address)
    else
      render :edit
    end
  end
  def profile   
  end

  def profile_update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :profile
    end
  end
  def ready
  end

  private
  def address_params
    params.require(:address).permit(:postal_code, :prefecture, :city, :address, :apartment)
  end

  def set_user
    #@user = User.find(params[:id])
  end

  def set_address
    @address = Address.find(params[:id])
  end

  def set_category
    @parents = Category.all.order("id ASC").limit(13)
  end
  def user_params
    params.require(:user).permit(
      :nickname,
      :introduction,
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage_side.html.haml
.side-content
  %nav.mypage-nav
    %ul.mypage-nav-list
      //%li
      //  =link_to user_path(current_user.id), class: "mypage-nav-list-item" do
      //    マイページ
      //    %i.icon-arrow-right
      //%li
      //  =link_to ready_users_path, class: "mypage-nav-list-item" do
      //    お知らせ
      //    %i.icon-arrow-right
      %li 
        =link_to users_profile_path, class: "mypage-nav-list-item" do
          やることリスト
          %i.icon-arrow-right 
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          いいね！一覧
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          出品する
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          出品した商品 - 出品中
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          出品した商品 - 取引中
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          出品した商品 - 売却済み
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          購入した商品 - 取引中
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          購入した商品 - 過去の取引
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          ニュース一覧
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          評価一覧
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          ガイド
          %i.icon-arrow-right
      %li
        =link_to products_path, class: "mypage-nav-list-item" do
          お問い合わせ
          %i.icon-arrow-right
    
    %h3.mypage-nav-head-setting 設定
    %ul.mypage-nav-list-setting
      %li
        =link_to users_profile_path, class: "mypage-nav-list-setting-item" do
          プロフィール
          %i.icon-arrow-right
      %li
        =link_to user_registration_path, class: "mypage-nav-list-setting-item" do
          発送元・お届け先住所変更
          %i.icon-arrow-right
      %li
        =link_to new_user_password_path, class: "mypage-nav-list-setting-item" do
          支払い方法
          %i.icon-arrow-right
      %li
        =link_to new_user_password_path, class: "mypage-nav-list-setting-item" do
          メール/パスワード
          %i.icon-arrow-right
      %li
        =link_to users_profile_path, class: "mypage-nav-list-setting-item" do
          本人情報
          %i.icon-arrow-right
      %li
        =link_to new_user_password_path, class: "mypage-nav-list-setting-item" do
          電話番号の確認
          %i.icon-arrow-right
      %li
        =link_to destroy_user_session_path, method: :delete, class: "mypage-nav-list-setting-item" do
          ログアウト
          %i.icon-arrow-right

app/views/users/edit.html.haml
= render "home/header_login"
- breadcrumb :edit_profile
= render "layouts/breadcrumbs"
=render "mypage_side"
//.mypage_a  
//  %main.mypage-contents.clearfix
    .edit-main__content
      .edit-main__content--title
        本人情報の登録
      .edit-main__content--introduction
        お客様の本人情報をご登録ください。
        %br/
        登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        .edit-main__content--introduction-append
          本人確認書類のアップロードについて＞

      %ul.edit-main__content--box

        %li.box__info
          .box__info--label
            お名前
          .box__info--user
            = "#{@user.first_name} #{@user.last_name}"

        %li.box__info
          .box__info--label
            お名前 カナ
          .box__info--user
            = "#{@user.first_name_kana} #{@user.last_name_kana}"

        %li.box__info
          .box__info--label
            生年月日
          .box__info--user
            = @user.birthday.strftime("%Y/%m/%d")

      .form-main__content
        = form_for(@address, url: user_path, method: :patch) do |f|
          = render "devise/shared/error_messages", resource: @address
          .form-group
            = f.label :郵便番号
            %span.form-group__optional 任意
            = f.text_field :postal_code, {autofocus: true, placeholder: "例）123-4567", class: "form-group__input"}
          .form-group
            = f.label :都道府県
            %span.form-group__optional 任意
            = f.select :prefecture, Address.prefectures.keys, {}, {class: "form-group__input"}
          .form-group
            = f.label :市町村
            %span.form-group__optional 任意
            = f.text_field :city, autofocus: true, placeholder: "例）札幌市", class: "form-group__input"
          .form-group
            = f.label :番地
            %span.form-group__optional 任意
            = f.text_field :address, autofocus: true, placeholder: "例）青葉1-1-1", class: "form-group__input"
          .form-group
            = f.label :建物名
            %span.form-group__optional 任意
            = f.text_field :apartment, autofocus: true, placeholder: "例）柳ビル103", class: "form-group__input"
          .form-group
            = f.submit "登録する", class: "btn-default btn-red"
          .form__info
            本人情報の登録について＞

  = render "products/foto"

= render "products/purchase"

= render "home/footer"

app/views/users/profile.html.haml
=render "devise/home/header_login"
//- breadcrumb :profile
//=render "layouts/breadcrumbs"
=render "mypage_side"
.mypage 
  %main.mypage__profile
    .main__profile
      .main__profile--form
        //=image_tag "#";
        .main__profile--header
          %h1 プロフィール
        .main__profile--detail
          //= form_for @user,url:profile_update_user_path(current_user), method: :patch,html:{class:"personal-input-form" } do |form|
        .main__profile__name 
        .main__profile__name--box
          .main__profile__name--img
            = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", height: "100", width: "100", class: "user-img"
        .main__profile__name--nickname
          //= form_with url: "profile_uses_pat" do |form|
          //:nickname
        .main__profile__name--message
          = form_with url: "profile_uses_path" do |form|
            フォーム内容
          //= form.text_area :introduction,class:'text-introduction',placeholder:"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪" 
        .main__form-edit
          変更する
          //= form.submit "変更する", class: "btn-default btn-red"
=render "products/middle__dl"
=render "products/footer"
=render "products/purchase"