config/routes.rb
Rails.application.routes.draw do
  get 'products/buy'
  get 'products/index'
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
    }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'creditcards', to: 'users/registrations#new_creditcard'
    post 'creditcards', to: 'users/registrations#create_creditcard'
  end
  root 'products#index'

 
  
    resources :users, only: [:show, :edit, :update]do
      member do
        get 'profile'
        patch 'profile_update'
        get 'logout'
      end
    end
  resources :products ,only: [:index,:new,:show,:create]do
    collection do
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      post 'purchase'
      get 'purchased'
      get 'buy'
      get 'reserve'
      patch 'reserved'
      patch 'reserve_cancel'
    end
end   
end

app/models/product.rb
class Product < ApplicationRecord
  enum brand: {"シャネル": 0, "グッチ": 1, "プラダ": 2, "エルメス": 3, "バレンシアガ": 4, "フェンディ": 5, "ボッテガ・ヴェネタ": 6, "ヴァレンチノ": 7, "サン・ローラン": 8, "アルマーニ": 9}
  enum status: {"新品・未使用": 1, "未使用に近い": 2,"目立った傷や汚れなし":3,"やや傷や汚れあり":4,"傷や汚れあり":5,"全体的に状態が悪い":6}
  enum postage: {"送料込み（出品者負担)":1, "送料込み（出品者負担）":2, "着払い（購入者負担）":3, "着払い（購入者負担）":4}
  enum shipping_date: {"1~2日で発送":1,  "2〜3日で発送":2,"4〜7日で発送":3}
  enum prefecture:{
    "北海道":1,"青森県":2,"岩手県":3,"宮城県":4,"秋田県":5,"山形県":6,"福島県":7,
    "茨城県":8,"栃木県":9,"群馬県":10,"埼玉県":11,"千葉県":12,"東京都":13,"神奈川県":14,
    "新潟県":15,"富山県":16,"石川県":17,"福井県":18,"山梨県":19,"長野県":20,
    "岐阜県":21,"静岡県":22,"愛知県":23,"三重県":24,
    "滋賀県":25,"京都府":26,"大阪府":27,"兵庫県":28,"奈良県":29,"和歌山県":30,
    "鳥取県":31,"島根県":32,"岡山県":33,"広島県":34,"山口県":35,
    "徳島県":36,"香川県":37,"愛媛県":38,"高知県":39,
    "福岡県":40,"佐賀県":41,"長崎県":42,"熊本県":43,"大分県":44,"宮崎県":45,"鹿児島県":46,"沖縄県":47
  }
  
  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy

  validates :name, :description, :status, :postage, :shipping_area, :shipping_days, presence: true
  validates :price,presence: true,numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  # validates :categories, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 13}
  accepts_nested_attributes_for :images
  # accepts_nested_attributes_for :images, allow_destroy: true
end

def get_category_children
  @category_children = Category.find("#{params[:parent_id]}").children
end

def get_category_grandchildren
  @category_grandchildren = Category.find("#{params[:child_id]}").children
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @parents = Category.where(ancestry:nil)
    @products = Product.includes(:images).order('created_at DESC')
    
  end

  def new
      @parents= Category.where(ancestry:nil)
    # if user_signed_in?   #一旦バリデーション外し中
      @product = Product.new
      @product.images.new
      # @product.images.new
    # else
      # redirect_to root_path
    # end

  end

  def create
    @product = Product.new(product_params)
    if @product.images.present? && @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json 
    end
    @product = Product.find(params[:id])
    @category_name = @product.category.root.name    
    @bigcategory_name = @product.category.parent .name
    @smallcategory_name = @product.category.name
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end
  
      
  def get_category_children
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  def get_category_grandchildren
    # @category_grandchildren = Category.find(id: "#{params[:child_id]}").children
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  


  def purchase
    @product_buyer= Product.find(params[:id])
    if @product_buyer.update(buyer_id: current_user.id)
      redirect_to purchased_product_path
      # 更新に成功した時の処理
    else
      render :purchase
      # 更新に失敗した時の処理
    end
  end

  private
    def product_params
      params.require(:product).permit(:name,:price,:description,:brand,:status,:postage,:shipping_area,:shipping_days,images_attributes: [:product_image,:_destroy,:id]).merge(user_id: current_user.id)
    end

    # カテゴリー
  def set_category
    @smallcategory = Category.where(@product.categories_id)
    @category = Category.where(Category.find(@product.categories_id).sub_sub) unless Category.find(@product.category_id).sub_sub == '0'
    @bigcategory = Category.where(Category.find(@product.categories_id).sub)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_bottom.html.haml
.bottom
  .image-bottom
    .image-bottom__left
      .image-bottom__left--top-text
        スマホでかんたんフリマアプリ
      .image-bottom__left--bottom-text
        今すぐ無料ダウンロード！
      .image-bottom__left--link
        .link__mercari
          = link_to image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg",width:'140',height:'40'
        .link__apple
          = link_to image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"
        .link__google
          = link_to image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"

    .image-bottom__right
    

app/views/products/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/products/_foto.html.haml
.foto
  = image_tag "http://furima.tokyo/assets/bg-appBanner-pict-ce684a4c4d5fa2da43c30a3839923591af75a642a3a906ad975065771ef3d72f.jpg",width:'100%',height:'400'
  .foto__box
    .foto__box--title だれでもかんたん、人生を変えるフリマアプリ
    .foto__box--text 今すぐ無料ダウンロード！
    .foto__box--icon
      = link_to "#" do
        = image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width:'180',height:'53'
      = link_to "#" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width:'180',height:'53'

app/views/products/_header.html.haml
.body
  .header__top
    .header__top__inner
      .header__top__inner__main
        %h1.header__top__inner__main__simbol
          = link_to root_path do
            = image_tag  "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg",width:'140',height:'40'
        .search__box
          %form{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
            %input{:name => "utf8", :type => "hidden", :value => "✓"}/
            %input.search__box__input{:name => "key", :placeholder => "キーワードから探す"}/
          %form.button_to{:action => "/?type=submit", :method => "post"}
            //%button{:type => "submit"}
            .search__box__icon
              = link_to "#" do
                = image_tag "http://furima.tokyo/assets/icon-search-60a83ada85216fe00789cd16065281694d9a08948275fef83683fadcf131d84d.svg",width:'20',height:'20'
            %input{:name => "authenticity_token", :type => "hidden", :value => "OBHVNGwRNEzn3yc5ciRJpZnfmtUjnE/QO/hj6tnrRnJP89jhpZTfkQgysVVgo2r34ymB0rcGL/jiRedonj8dLA=="}/
          %ul.result__lists
      .lists
        %ul.lists__left
          %li.lists__left__item--category
            =link_to("#") do 
              カテゴリー
              //%ul.category__parent
              //  - Category.roots.each do |parent|
              //    %li.parent__list
              //      = link_to parent.name
              //      %ul.category__child
              //        - parent.children.each do |child|
              //          %li.child__list
              //            =link_to child.name
              //            %ul.category__grandchild
              //              - child.children.each do |grandchild|
              //                %li.grandchild__list
              //                  = link_to grandchild.name
          %li.lists__left__item--bland
            =link_to("#") do  
              ブランド
            %ul.brands__pulldown.display_none
        %ul.lists__right
          %li.lists__right__item--login
            =link_to "#" do 
              ログイン
          %li.lists__right__item--new
            =link_to'#' do
              新規会員登録
      

app/views/products/_middle__dl.html.haml
%section.middle__dl
  = image_tag  "http://furima.tokyo/assets/bg-topMiddleDl-pict-5042a3aa7eef6dd93330080028e3a781daf47c390c00a4fb5d7e7b06caae68c9.jpg",width:'100%',height:'400'
  .middle__dl--inner
    %h2.middle__dl--subtitle 会員数日本一位
    %p.middle__dl--text
      FURIMAは、フリマアプリで最も人気。
      %br/
      出品・購入回数も業界最多です！
      %br/
      ほしかったあの商品に出会えるかもしれません。
    .btn
      = link_to "#" do
        = image_tag"http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width:'180',height:'53'
      = link_to "#" do
        = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width:'180',height:'53'

app/views/products/_picture.html.haml
.picture
    .top__intro
      .top__intro--subtitle
        FURIMAが選ばれる3つの理由
        .subtitle__after 
      %ul.pic__lists
        %li.pic__lists__left
          .pic__lists__left__pict
            %span.number1 
              %p 1
            = image_tag"http://furima.tokyo/assets/pict-reason-01-77b860b45f32923029756050dafc0f6df01a36675414b0f26f127c64a53baaea.jpg",width:300,height:'300'
          %h3.pic__lists__left__text
            %span 3分
            ですぐに出品
          %p.pic__lists__left__description
            スマホで入力するだけで簡単に出品できる！
        %li.pic__lists__center
          .pic__lists__center__pict
            %span.number2 
              %p 2
            = image_tag "http://furima.tokyo/assets/pict-reason-02-3471b96ea7b52654510992e57dc05af07926de0836200059b7fa4ead05ee4d56.jpg",width:300,height:'300'
          %h3.pic__lists__center__text
            %span シンプル
            で使いやすい
          %p.pic__lists__center__description
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.pic__lists__right
          .pic__lists__right__pict
            %span.number3 
              %p 3
            = image_tag "http://furima.tokyo/assets/pict-reason-03-1e3c743f3ba3db8c43987d2e257916a615aa8fc59c02bbc116f041a5580ec28f.jpg",width:300,height:'300'
          %h3.pic__lists__right__text
            手数料
            %span 業界最安
          %p.pic__lists__right__description
            最大3%でお得に出品&amp;購入！

app/views/products/_purchase.html.haml
.purchase__btn
  = link_to "#" do 
    %span.purchase__btn__text 
      出品する
    .purchase__btn__icon
      = image_tag "http://furima.tokyo/assets/icon_camera-968c5ebaa05319bf1e2ad7508f852dd712504a4d26a1930d8bd87ec03ebcc37a.svg",width:'55',height:'55'

app/views/products/_simbol.html.haml
.header
  .header__simbol
    =image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg", width:'150',height:'75'

app/views/products/_single__footer.html.haml
%footer.single-footer__a
  %nav
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー", "#"
      %li
        = link_to "フリマ 利用規約", "#"
      %li
        = link_to "特定商取引に関する表記", "#"
      .header__simbol__bottom
    =image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg", width:'100',height:'40'
  %p
    %small 
      © FURIMA, Inc. 

app/views/products/_single_footer.html.haml
%footer.single-footer__a
  %nav
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー", "#"
      %li
        = link_to "フリマ 利用規約", "#"
      %li
        = link_to "特定商取引に関する表記", "#"
      .header__simbol__bottom
    =image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg", width:'100',height:'40'
  %p
    %small 
      © FURIMA, Inc. 

app/views/products/index.html.haml
.body
  .header__top
    .header__top__inner
      .header__top__inner__main
        %h1.header__top__inner__main__simbol
          = link_to root_path do
            = image_tag  "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg",width:'140',height:'40'
        .search__box
          %form{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
            %input{:name => "utf8", :type => "hidden", :value => "✓"}/
            %input.search__box__input{:name => "key", :placeholder => "キーワードから探す"}/
          %form.button_to{:action => "/?type=submit", :method => "post"}
            //%button{:type => "submit"}
            .search__box__icon
              = link_to "#" do
                = image_tag "http://furima.tokyo/assets/icon-search-60a83ada85216fe00789cd16065281694d9a08948275fef83683fadcf131d84d.svg",width:'20',height:'20'
            %input{:name => "authenticity_token", :type => "hidden", :value => "OBHVNGwRNEzn3yc5ciRJpZnfmtUjnE/QO/hj6tnrRnJP89jhpZTfkQgysVVgo2r34ymB0rcGL/jiRedonj8dLA=="}/
          %ul.result__lists
      .lists
        %ul.lists__left
          %li.categories
            =link_to("#") do 
              カテゴリー
              %ul.category__parent
                //- @parents.each do |parent|
                //  %li.parent__list
                //    = link_to parent.name
                //    %ul.category__child
                //      - parent.children.each do |child|
                //        %li.child__list
                //          =link_to child.name
                //          %ul.category__grandchild
                //            - child.children.each do |grandchild|
                //              %li.grandchild__list
                //                = link_to grandchild.name
          %li.lists__left__item--bland
            =link_to("#") do  
              ブランド
            %ul.brands__pulldown.display_none
        %ul.lists__right
          -if user_signed_in?
            %li.lists__right__item--login     
              =link_to "マイページ", profile_user_path(current_user.id),class:"mypage"
          -else 
            %li.lists__right__item--login
              =link_to(new_user_session_path) do 
                ログイン
            %li.lists__right__item--new
              =link_to(new_user_registration_path) do 
                新規会員登録
  .main__top
    = image_tag "http://furima.tokyo/assets/bg-mainVisual-pict_pc-a1a4be0d864c29338b03d163957f9fd26b20f7c1fa0d05c17b603ec54d249ebe.jpg",width:'100%',height:'540'
    %section.main__top__content
      %h2.main__top__content--title
        %br/
        人生を変えるフリマアプリ
      %p.main__top__content--subtitle
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .main__top__content--btn
        = link_to "#" do
          = image_tag"http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width:'180',height:'53'
        = link_to "#" do
          = image_tag"http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width:'180',height:'53'
  .picture
    .top__intro
      .top__intro--subtitle
        FURIMAが選ばれる3つの理由
        .subtitle__after 
      %ul.pic__lists
        %li.pic__lists__left
          .pic__lists__left__pict
            %span.number1 
              %p 1
            = image_tag"http://furima.tokyo/assets/pict-reason-01-77b860b45f32923029756050dafc0f6df01a36675414b0f26f127c64a53baaea.jpg",width:300,height:'300'
          %h3.pic__lists__left__text
            %span 3分
            ですぐに出品
          %p.pic__lists__left__description
            スマホで入力するだけで簡単に出品できる！
        %li.pic__lists__center
          .pic__lists__center__pict
            %span.number2 
              %p 2
            = image_tag "http://furima.tokyo/assets/pict-reason-02-3471b96ea7b52654510992e57dc05af07926de0836200059b7fa4ead05ee4d56.jpg",width:300,height:'300'
          %h3.pic__lists__center__text
            %span シンプル
            で使いやすい
          %p.pic__lists__center__description
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.pic__lists__right
          .pic__lists__right__pict
            %span.number3
              %p 3
            = image_tag "http://furima.tokyo/assets/pict-reason-03-1e3c743f3ba3db8c43987d2e257916a615aa8fc59c02bbc116f041a5580ec28f.jpg",width:300,height:'300'
          %h3.pic__lists__right__text
            手数料
            %span 業界最安
          %p.pic__lists__right__description
            最大3%でお得に出品&amp;購入！
    %section.middle__dl
      = image_tag  "http://furima.tokyo/assets/bg-topMiddleDl-pict-5042a3aa7eef6dd93330080028e3a781daf47c390c00a4fb5d7e7b06caae68c9.jpg",width:'100%',height:'400'

      .middle__dl--inner
        %h2.middle__dl--subtitle 会員数日本一位
        %p.middle__dl--text
          FURIMAは、フリマアプリで最も人気。
          %br/
          出品・購入回数も業界最多です！
          %br/
          ほしかったあの商品に出会えるかもしれません。
        .btn
          = link_to "#" do
            = image_tag"http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width:'180',height:'53'
          = link_to "#" do
            = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width:'180',height:'53'
    %section.features
      %h2.head 
        FURIMAの特徴
        .head__after
      .items
        %section.items__item
          %figure.items__item--img
            = image_tag "http://furima.tokyo/assets/icon-01-7f6abf70ea7deaed9ab5d8b6d5cb796250e3e292b9ecdc559ebe6492c31fdab8.svg",width:'220',height:'340'
          %h3.items__item--subtitle 簡単に売り買いできる
          %p.items__item--detail
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        %section.items__item
          %figure.items__item--img
            = image_tag "http://furima.tokyo/assets/icon-03-9c0d78266a316fec7b738dcf5c68dd987afb9655b13fd2cd5d30bcf09e827694.svg",width:'220',height:'340'
          %h3.items__item--subtitle 売上金は即日振込みに対応
          %p.items__item--detail
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        %section.items__item
          %figure.items__item--img
            = image_tag "http://furima.tokyo/assets/icon-04-c4052f85cd6e1f62ea8cac8c55277d7fa4bda971d924f8a2afe72eea6558fa85.svg",width:'220',height:'340'
          %h3.items__item--subtitle 様々な支払いに対応
          %p.items__item--detail
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    %section.pickup__container
      %h2.head ピックアップカテゴリー
      .product_box
        .product__head
          = link_to "#" do
            %h3.title 新規投稿商品
        .product__lists
          .product__lists__list
            = link_to "/products/8" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/16/IMG_9072.JPG",width:'220',height:'150'
              .product__lists__list--body
                %h3.name ee
                .details
                  %ul
                    %li 10000円
                    %li
                      %i.fa.fa-star
                      0
                  %p (税込)
          .product__lists__list
            = link_to "/products/3" do
              %figure.product__lists__list--img
                = image_tag  "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png",width:'220',height:'150'
              .product__lists__list--body
                %h3.name product3
                .details
                  %ul
                    %li 30000円
                    %li
                      %i.fa.fa-star  
                      0
                  %p (税込)
          .product__lists__list
            = link_to "/products/2" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png",width:'220',height:'150'
              .product__lists__list--body
                %h3.name product2
                .details
                  %ul
                    %li 20000円
                    %li
                      %i.fas.fa-star
                      0
                  %p (税込)
          .product__lists__list
            = link_to "/products/1" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png",width:'220',height:'150'
              .product__lists__list--body
                %h3.name product2
                .details
                  %ul
                    %li 10000円
                    %li
                      %i.fa.fa-star
                      1
                  %p (税込)
    %section.pickup__container
      %h2.head ピックアップブランド
      .product__box
        .product__head
          = link_to "#" do
            %h3.title アーカイバ
        .product__lists
          .product__lists__list
            = link_to "/products/8" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/16/IMG_9072.JPG",width:'220',height:'150'
              .product__lists__list--body
                %h3.name ee
                .details
                  %ul
                    %li 10000円
                    %li
                      %i.fa.fa-star
                      0
                  %p (税込)
          .product__lists__list
            = link_to "/products/3" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png",width:'220',height:'150'
              .product__lists__list--body
                %h3.name product3
                .details
                  %ul
                    %li 30000円
                    %li
                      %i.fa.fa-star
                      0
                  %p (税込)
          .product__lists__list
            = link_to "/products/2" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png",width:'220',height:'150'
              .product__lists__list--body
                %h3.name product2
                .details
                  %ul
                    %li 20000円
                    %li
                      %i.fa.fa-star
                      0
                  %p (税込)
          .product__lists__list
            = link_to "/products/1" do
              %figure.product__lists__list--img
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png",width:'220',height:'150'
              .product__lists__list--body
                %h3.name product1
                .details
                  %ul
                    %li 10000円
                    %li
                      %i.fa.fa-star
                      1
                  %p (税込)
  .foto
    = image_tag "http://furima.tokyo/assets/bg-appBanner-pict-ce684a4c4d5fa2da43c30a3839923591af75a642a3a906ad975065771ef3d72f.jpg",width:'100%',height:'400'
    .foto__box
      .foto__box--title だれでもかんたん、人生を変えるフリマアプリ
      .foto__box--text 今すぐ無料ダウンロード！
      .foto__box--icon
        = link_to "#" do
          = image_tag "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg",width:'180',height:'53'
        = link_to "#" do
          = image_tag "http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg",width:'180',height:'53'
  .footer
    %ul.contents
      %li.contents__left
        %h2.contents__left__head FURIMAについて
        %ul
          %li
            = link_to "#" do 
              会社概要（運営会社）
          %li
            = link_to "#" do 
              プライバシーポリシー
          %li
            = link_to "#" do 
              FURIMA利用規約
          %li
            = link_to "#" do 
              ポイントに関する特約
      %li.contents__center
        %h2.contents__center__head FURIMAを見る
        %ul
          %li
            = link_to "#" do 
              カテゴリー一覧
          %li
            = link_to "#" do 
              ブランド一覧
      %li.contents__right
        %h2.contents__right__head ヘルプ＆ガイド
        %ul
          %li
            = link_to "#" do 
              FURIMAガイド
          %li
            = link_to "#" do 
              FURIMAロゴ利用ガイドライン
          %li
            = link_to "#" do 
              お知らせ
    .footer__logo
      = link_to "/" do
        = image_tag "http://furima.tokyo/assets/logo-white-f61961ed5170064c5f33dd4524bdceeb5a5df2c83eb76fba31143f63fbab2c5e.svg",width:'160',height:'46'
      %p 
        = link_to "#" do 
          © FURIMA   
      .purchase__btn
        = link_to (new_product_path) do 
          %span.purchase__btn__text 
            出品する
          .purchase__btn__icon
            = image_tag "http://furima.tokyo/assets/icon_camera-968c5ebaa05319bf1e2ad7508f852dd712504a4d26a1930d8bd87ec03ebcc37a.svg",width:'55',height:'55'